import type { MediaAsset } from "./types";

export const mediaAssets: MediaAsset[] = [
  {
    id: "asta-tengen-logo-svg",
    type: "image",
    src: "/media/brand/astatengenlogo.svg",
    alt: "Logo monogram Asta Tengen.",
    page: "global",
    section: "header, footer, metadata",
    aspectRatio: "1:1",
    source: "owned",
    sourceUrl: "local:src/image/astatengenlogo.svg",
    licenseType: "owned by Asta Tengen",
    downloadedAt: "2026-06-14",
    approved: true,
  },
  {
    id: "asta-tengen-logo-png",
    type: "image",
    src: "/media/brand/logoastatengen.png",
    alt: "Logo Asta Tengen dalam format raster.",
    page: "global",
    section: "fallback brand asset",
    aspectRatio: "1:1",
    source: "owned",
    sourceUrl: "local:src/image/logoastatengen.png",
    licenseType: "owned by Asta Tengen",
    downloadedAt: "2026-06-14",
    approved: true,
  },
  {
    id: "achmad-roychan-portrait",
    type: "image",
    src: "/media/people/roychan.jpeg",
    alt: "Potret Achmad Roychan, pendiri Asta Tengen.",
    page: "/tentang",
    section: "pendiri",
    aspectRatio: "1088:1446",
    source: "owned",
    sourceUrl: "local:src/image/roychan.jpeg",
    licenseType: "provided by Asta Tengen",
    downloadedAt: "2026-06-14",
    approved: true,
  },
  {
    id: "aditya-sendy-portrait",
    type: "image",
    src: "/media/people/aditya.jpeg",
    alt: "Potret Aditya Sendy Ardiansyah, pendiri Asta Tengen.",
    page: "/tentang",
    section: "pendiri",
    aspectRatio: "765:1024",
    source: "owned",
    sourceUrl: "local:src/image/aditya.jpeg",
    licenseType: "provided by Asta Tengen",
    downloadedAt: "2026-06-14",
    approved: true,
  },
  {
    id: "aneka-jajanan-desktop-screenshot",
    type: "image",
    src: "/media/projects/aneka-jajanan-desktop.png",
    alt: "Screenshot desktop website Aneka Jajanan Mutiara.",
    page: "/proyek/aneka-jajanan-mutiara",
    section: "case study preview",
    aspectRatio: "1440:4349",
    source: "owned",
    sourceUrl: "https://anekajajanan.vercel.app/",
    licenseType: "website project by Asta Tengen",
    downloadedAt: "2026-06-15",
    approved: true,
  },
  {
    id: "aneka-jajanan-mobile-screenshot",
    type: "image",
    src: "/media/projects/aneka-jajanan-mobile.png",
    alt: "Screenshot mobile website Aneka Jajanan Mutiara.",
    page: "/proyek/aneka-jajanan-mutiara",
    section: "case study preview",
    aspectRatio: "390:6955",
    source: "owned",
    sourceUrl: "https://anekajajanan.vercel.app/",
    licenseType: "website project by Asta Tengen",
    downloadedAt: "2026-06-15",
    approved: true,
  },
  {
    id: "ruang-rapi-desktop-screenshot",
    type: "image",
    src: "/media/projects/ruangrapi-desktop.png",
    alt: "Screenshot desktop website Ruang Rapi.",
    page: "/proyek/ruang-rapi-laundry",
    section: "case study preview",
    aspectRatio: "1440:4784",
    source: "owned",
    sourceUrl: "https://ruangrapi.vercel.app/",
    licenseType: "internal project by Asta Tengen",
    downloadedAt: "2026-06-15",
    approved: true,
  },
  {
    id: "ruang-rapi-mobile-screenshot",
    type: "image",
    src: "/media/projects/ruangrapi-mobile.png",
    alt: "Screenshot mobile website Ruang Rapi.",
    page: "/proyek/ruang-rapi-laundry",
    section: "case study preview",
    aspectRatio: "780:18158",
    source: "owned",
    sourceUrl: "https://ruangrapi.vercel.app/",
    licenseType: "internal project by Asta Tengen",
    downloadedAt: "2026-06-15",
    approved: true,
  },
];
