import type { MediaAsset } from "./types";

export const mediaAssets: MediaAsset[] = [
  {
    id: "sector-one-logo-svg",
    type: "image",
    src: "/media/brand/logosectorone.svg",
    alt: "Logo Sector One.",
    page: "global",
    section: "header, footer, metadata",
    aspectRatio: "192:217",
    source: "owned",
    sourceUrl: "local:src/image/logosectorone.svg",
    licenseType: "owned by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "achmad-roychan-portrait",
    type: "image",
    src: "/media/people/roychan.jpeg",
    alt: "Potret Achmad Roychan, pendiri Sector One.",
    page: "/tentang",
    section: "pendiri",
    aspectRatio: "1088:1446",
    source: "owned",
    sourceUrl: "local:src/image/roychan.jpeg",
    licenseType: "provided by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "ruang-rapi-desktop-screenshot",
    type: "image",
    src: "/media/projects/ruangrapi-desktop.png",
    alt: "Screenshot desktop website Ruang Rapi.",
    page: "/proyek/ruang-rapi-laundry",
    section: "case study preview",
    aspectRatio: "1440:4784",
    source: "owned",
    sourceUrl: "https://ruangrapi.vercel.app/",
    licenseType: "internal project by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "ruang-rapi-mobile-screenshot",
    type: "image",
    src: "/media/projects/ruangrapi-mobile.png",
    alt: "Screenshot mobile website Ruang Rapi.",
    page: "/proyek/ruang-rapi-laundry",
    section: "case study preview",
    aspectRatio: "780:18158",
    source: "owned",
    sourceUrl: "https://ruangrapi.vercel.app/",
    licenseType: "internal project by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "aneka-jajanan-desktop-screenshot",
    type: "image",
    src: "/media/projects/aneka-jajanan-desktop.png",
    alt: "Screenshot desktop website Aneka Jajanan Mutiara.",
    page: "/proyek/aneka-jajanan-mutiara",
    section: "case study preview",
    aspectRatio: "1440:4349",
    source: "owned",
    sourceUrl: "https://anekajajanan.vercel.app/",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "aneka-jajanan-mobile-screenshot",
    type: "image",
    src: "/media/projects/aneka-jajanan-mobile.png",
    alt: "Screenshot mobile website Aneka Jajanan Mutiara.",
    page: "/proyek/aneka-jajanan-mutiara",
    section: "case study preview",
    aspectRatio: "390:6955",
    source: "owned",
    sourceUrl: "https://anekajajanan.vercel.app/",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "satu-cukur-desktop-screenshot",
    type: "image",
    src: "/media/projects/satucukur-desktop.png",
    alt: "Screenshot desktop website Satu Cukur Barbershop.",
    page: "/proyek/satu-cukur-barbershop",
    section: "case study preview",
    aspectRatio: "1440:4784",
    source: "owned",
    sourceUrl: "local:projects/satucukur-desktop.png",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "satu-cukur-mobile-screenshot",
    type: "image",
    src: "/media/projects/satucukur-mobile.png",
    alt: "Screenshot mobile website Satu Cukur Barbershop.",
    page: "/proyek/satu-cukur-barbershop",
    section: "case study preview",
    aspectRatio: "780:18158",
    source: "owned",
    sourceUrl: "local:projects/satucukur-mobile.png",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "klinik-nara-desktop-screenshot",
    type: "image",
    src: "/media/projects/kliniknara-desktop.png",
    alt: "Screenshot desktop website Klinik Nara.",
    page: "/proyek/klinik-nara-aesthetic",
    section: "case study preview",
    aspectRatio: "1440:4784",
    source: "owned",
    sourceUrl: "local:projects/kliniknara-desktop.png",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "klinik-nara-mobile-screenshot",
    type: "image",
    src: "/media/projects/kliniknara-mobile.png",
    alt: "Screenshot mobile website Klinik Nara.",
    page: "/proyek/klinik-nara-aesthetic",
    section: "case study preview",
    aspectRatio: "780:18158",
    source: "owned",
    sourceUrl: "local:projects/kliniknara-mobile.png",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "garis-mesin-desktop-screenshot",
    type: "image",
    src: "/media/projects/garismesin-desktop.png",
    alt: "Screenshot desktop website Bengkel Garis Mesin.",
    page: "/proyek/bengkel-garis-mesin",
    section: "case study preview",
    aspectRatio: "1440:4784",
    source: "owned",
    sourceUrl: "local:projects/garismesin-desktop.png",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
  {
    id: "garis-mesin-mobile-screenshot",
    type: "image",
    src: "/media/projects/garismesin-mobile.png",
    alt: "Screenshot mobile website Bengkel Garis Mesin.",
    page: "/proyek/bengkel-garis-mesin",
    section: "case study preview",
    aspectRatio: "780:18158",
    source: "owned",
    sourceUrl: "local:projects/garismesin-mobile.png",
    licenseType: "internal concept study by Sector One",
    downloadedAt: "2026-06-16",
    approved: true,
  },
];
