import type { ServicePackage } from "./types";

export const services: ServicePackage[] = [
  {
    slug: "starter-presence",
    name: "Starter Presence",
    summary: "Website ringkas untuk usaha yang membutuhkan identitas digital dasar.",
    price: "Rp100.000",
    estimate: "1-2 hari kerja",
    revisions: "1 putaran",
    renewal: "Rp0 selama memakai subdomain",
    warranty: "7 hari",
    assistLimit: "Asta Assist tidak termasuk",
    assistActive: "Tidak termasuk",
    includes: [
      "satu halaman",
      "struktur desain tetap",
      "profil usaha",
      "daftar layanan singkat",
      "alamat",
      "jam operasional",
      "Google Maps",
      "tombol WhatsApp",
      "tampilan mobile",
      "subdomain Asta Tengen",
    ],
    assistNotes: [
      "Harga paket ini sengaja dipertahankan sangat rendah dan tidak memiliki cukup ruang untuk biaya pengembangan serta pengoperasian AI.",
    ],
    domainHosting:
      "Tidak termasuk domain pribadi, hosting khusus, dan Asta Assist. Website menggunakan subdomain Asta Tengen.",
    constraints: ["Tidak mencakup Asta Assist.", "Tidak termasuk domain pribadi dan hosting khusus."],
  },
  {
    slug: "launch-page-ai",
    name: "Launch Page AI",
    summary: "Landing page untuk mempromosikan satu produk, layanan, acara, kelas, dan kampanye.",
    price: "Rp1.350.000",
    estimate: "5-7 hari kerja",
    revisions: "2 putaran",
    renewal: "Rp750.000 per tahun",
    warranty: "14 hari",
    assistLimit: "Maksimal 300 respons AI per bulan dan maksimal 15 sumber informasi",
    assistActive: "Masa aktif AI selama tiga bulan",
    includes: [
      "satu halaman",
      "maksimal tujuh section",
      "desain sesuai identitas bisnis",
      "formulir kontak",
      "tombol WhatsApp",
      "galeri",
      "Google Maps",
      "SEO dasar",
      "domain .com",
      "hosting dan SSL selama satu tahun",
      "Asta Assist",
    ],
    assistNotes: [
      "Asta Assist pada paket ini berfokus pada pertanyaan promosi, harga, manfaat, jadwal, lokasi, dan cara pemesanan.",
    ],
    domainHosting:
      "Sudah termasuk domain .com selama satu tahun, hosting selama satu tahun, SSL, konfigurasi DNS, pemasangan website, instalasi Asta Assist, database pengetahuan, penggunaan AI sesuai batas paket, pemantauan kesalahan dasar, dan backup awal.",
    constraints: ["Harga berlaku selama ruang lingkup proyek tidak berubah."],
  },
  {
    slug: "business-profile-ai",
    name: "Business Profile AI",
    summary: "Website resmi untuk memperkenalkan usaha, perusahaan, lembaga, dan jasa profesional.",
    price: "Rp2.950.000",
    estimate: "9-13 hari kerja",
    revisions: "3 putaran",
    renewal: "Rp1.100.000 per tahun",
    warranty: "30 hari",
    assistLimit: "Maksimal 750 respons AI per bulan dan maksimal 30 sumber informasi",
    assistActive: "Masa aktif AI selama enam bulan",
    includes: [
      "maksimal lima halaman",
      "beranda",
      "tentang",
      "layanan",
      "proyek atau galeri",
      "kontak",
      "formulir",
      "WhatsApp",
      "Google Maps",
      "SEO dasar",
      "domain .com",
      "hosting dan SSL selama satu tahun",
      "Asta Assist",
      "pengumpulan data calon pelanggan",
      "pengarahan percakapan ke WhatsApp",
    ],
    assistNotes: [
      "Asta Assist pada paket ini dapat memahami profil bisnis, seluruh layanan, harga, proses kerja, cakupan layanan, lokasi, jam operasional, dan pertanyaan umum.",
    ],
    domainHosting:
      "Sudah termasuk domain .com selama satu tahun, hosting selama satu tahun, SSL, konfigurasi DNS, pemasangan website, instalasi Asta Assist, database pengetahuan, penggunaan AI sesuai batas paket, pemantauan kesalahan dasar, dan backup awal.",
    constraints: ["Harga berlaku selama ruang lingkup proyek tidak berubah."],
  },
  {
    slug: "product-catalogue-ai",
    name: "Product Catalogue AI",
    summary: "Website katalog untuk menampilkan dan membantu pelanggan menemukan produk.",
    price: "Rp4.750.000",
    estimate: "14-20 hari kerja",
    revisions: "3 putaran",
    renewal: "Rp1.500.000 per tahun",
    warranty: "45 hari",
    assistLimit: "Maksimal 1.000 respons AI per bulan dan informasi maksimal 30 produk",
    assistActive: "Masa aktif AI selama satu tahun",
    includes: [
      "maksimal tujuh halaman utama",
      "kategori produk",
      "halaman detail produk",
      "pencarian produk",
      "dashboard pengelolaan",
      "input awal maksimal 30 produk",
      "pemesanan melalui WhatsApp",
      "SEO dasar",
      "domain .com",
      "hosting dan SSL selama satu tahun",
      "Asta Assist",
      "pencarian produk melalui percakapan",
      "rekomendasi produk berdasarkan data katalog",
      "pengarahan ke halaman produk",
    ],
    assistNotes: [
      "Asta Assist tidak boleh menyatakan stok tersedia kecuali website telah memiliki data stok yang selalu diperbarui.",
    ],
    domainHosting:
      "Sudah termasuk domain .com selama satu tahun, hosting selama satu tahun, SSL, konfigurasi DNS, pemasangan website, instalasi Asta Assist, database pengetahuan, penggunaan AI sesuai batas paket, pemantauan kesalahan dasar, dan backup awal.",
    constraints: ["Harga berlaku selama ruang lingkup proyek tidak berubah."],
  },
  {
    slug: "commerce-ai",
    name: "Commerce AI",
    summary: "Website toko online untuk menampilkan produk dan menerima pesanan.",
    price: "Rp7.750.000",
    estimate: "20-28 hari kerja",
    revisions: "4 putaran",
    renewal: "Rp2.200.000 per tahun",
    warranty: "60 hari",
    assistLimit: "Maksimal 1.500 respons AI per bulan",
    assistActive: "Masa aktif AI selama satu tahun",
    includes: [
      "katalog produk",
      "kategori",
      "detail produk",
      "keranjang",
      "checkout",
      "pembayaran digital standar",
      "dashboard pesanan",
      "dashboard produk",
      "input awal maksimal 30 produk",
      "domain .com",
      "hosting dan SSL selama satu tahun",
      "SEO dasar",
      "Asta Assist",
      "pencarian produk melalui percakapan",
      "penjelasan produk",
      "pengarahan menuju produk dan checkout",
      "pengumpulan kebutuhan pelanggan",
      "pengarahan ke WhatsApp",
    ],
    assistNotes: [
      "Asta Assist tidak memproses pembayaran di dalam percakapan.",
      "Asta Assist tidak boleh mengubah harga, status pembayaran, status pesanan, dan status pengiriman.",
    ],
    domainHosting:
      "Sudah termasuk domain .com selama satu tahun, hosting selama satu tahun, SSL, konfigurasi DNS, pemasangan website, instalasi Asta Assist, database pengetahuan, penggunaan AI sesuai batas paket, pemantauan kesalahan dasar, dan backup awal.",
    constraints: ["Harga berlaku selama ruang lingkup proyek tidak berubah."],
  },
  {
    slug: "signature-build-ai",
    name: "Signature Build AI",
    summary: "Website custom untuk bisnis yang memiliki kebutuhan lebih spesifik.",
    price: "Rp10.000.000",
    estimate: "28-40 hari kerja",
    revisions: "4 putaran",
    renewal: "Rp2.900.000 per tahun",
    warranty: "90 hari",
    assistLimit: "Maksimal 2.500 respons AI per bulan",
    assistActive: "Masa aktif AI selama satu tahun",
    includes: [
      "desain UI custom",
      "maksimal sepuluh halaman utama",
      "CMS",
      "satu modul bisnis khusus",
      "formulir lanjutan",
      "satu integrasi layanan pihak ketiga",
      "analytics",
      "SEO teknis dasar",
      "dokumentasi",
      "pelatihan pengelolaan",
      "domain .com",
      "hosting dan SSL selama satu tahun",
      "Asta Assist",
      "knowledge base custom",
      "pengumpulan lead",
      "satu alur tindakan khusus",
      "pengarahan ke WhatsApp",
    ],
    assistNotes: [
      "Satu alur tindakan khusus dapat berupa pengumpulan permintaan konsultasi, penyaringan kebutuhan pelanggan, pencarian layanan, pencarian katalog, atau pencatatan permintaan booking.",
      "Signature Build AI tidak mencakup sistem AI enterprise, voice assistant, WhatsApp AI resmi, multi-agent, CRM kompleks, ERP, serta automasi lintas aplikasi dalam jumlah besar.",
    ],
    domainHosting:
      "Sudah termasuk domain .com selama satu tahun, hosting selama satu tahun, SSL, konfigurasi DNS, pemasangan website, instalasi Asta Assist, database pengetahuan, penggunaan AI sesuai batas paket, pemantauan kesalahan dasar, dan backup awal.",
    constraints: ["Harga berlaku selama ruang lingkup proyek tidak berubah."],
  },
];

export const serviceNotes = {
  estimateStartsAfter: [
    "pembayaran awal diterima",
    "brief disepakati",
    "logo diterima",
    "teks diterima",
    "foto dan video diterima",
    "data produk diterima",
    "daftar harga diterima",
    "FAQ diterima",
    "kebijakan bisnis diterima",
    "informasi untuk Asta Assist telah disetujui",
  ],
  assistRevisionIncludes: [
    "koreksi jawaban",
    "koreksi informasi",
    "penyesuaian gaya bahasa",
    "perubahan kalimat pembuka",
    "perubahan pertanyaan yang disarankan",
    "perbaikan pengarahan menuju WhatsApp",
    "perbaikan sumber pengetahuan",
  ],
  assistRevisionExcludes: [
    "penambahan fungsi AI baru",
    "integrasi platform baru",
    "penambahan automasi",
    "perubahan sistem AI",
    "perubahan struktur bisnis",
    "penambahan data dalam jumlah besar",
    "pembangunan ulang chatbot",
  ],
  annualRenewalCovers: [
    "domain .com",
    "hosting",
    "SSL",
    "backup",
    "pembaruan sistem dasar",
    "pemeriksaan keamanan dasar",
    "pemeriksaan fungsi Asta Assist",
    "biaya penggunaan AI sesuai batas paket",
    "pemeliharaan knowledge base",
    "satu pembaruan informasi AI setiap tiga bulan",
  ],
  aiUsage: [
    "Ketika jumlah respons melewati batas paket, Asta Assist dihentikan sementara sampai periode berikutnya.",
    "Klien dapat menambah kapasitas Rp75.000 untuk tambahan 500 respons AI.",
    "Penambahan kapasitas tidak mengubah fungsi Asta Assist.",
    "Respons AI dihitung ketika sistem menghasilkan satu balasan kepada pengunjung.",
    "Pesan pembuka otomatis tidak dihitung sebagai respons AI.",
  ],
  warrantyExcludes: [
    "informasi bisnis yang salah dari klien",
    "data yang sudah tidak berlaku",
    "perubahan harga yang belum dikirim kepada Asta Tengen",
    "kehabisan batas penggunaan",
    "gangguan penyedia AI",
    "gangguan hosting",
    "penyalahgunaan oleh pengunjung",
    "permintaan fitur baru",
    "perubahan alur bisnis",
    "perubahan knowledge base dalam jumlah besar",
  ],
};

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
