import type { ServicePackage } from "./types";

export const services: ServicePackage[] = [
  {
    slug: "one-page-starter",
    name: "One Page Starter",
    summary: "Untuk usaha kecil yang butuh halaman online sederhana berisi informasi bisnis, layanan, lokasi, dan tombol WhatsApp.",
    price: "Rp199.000",
    estimate: "1-2 hari setelah materi lengkap",
    revisions: "1x revisi kecil",
    renewal: "Rp199.000 per tahun",
    warranty: "7 hari",
    assistLimit: "Dukungan teknis via WhatsApp selama masa garansi",
    assistActive: "Masa garansi aktif selama 7 hari setelah rilis",
    includes: [
      "1 halaman website sederhana",
      "maksimal 5 section",
      "menggunakan template dari Sector One",
      "konten utama dari klien",
      "tombol WhatsApp",
      "Google Maps embed",
      "tampilan responsif mobile",
      "live menggunakan subdomain",
    ],
    assistNotes: [
      "Cocok untuk usaha kecil yang ingin punya link resmi dengan ruang lingkup ringan.",
      "Pembayaran dilakukan penuh di awal sebelum pengerjaan dimulai.",
    ],
    domainHosting:
      "Menggunakan subdomain Sector One. Domain pribadi, hosting khusus, dan biaya pihak ketiga tidak termasuk.",
    constraints: [
      "Tidak termasuk domain pribadi (custom domain).",
      "Tidak ada desain layout custom dari nol.",
      "Tidak termasuk copywriting panjang.",
      "Tidak mencakup halaman tambahan, dashboard, toko online, atau fitur khusus.",
      "Tidak mencakup revisi besar, meeting panjang, atau perubahan konsep total.",
    ],
  },
  {
    slug: "business-profile",
    name: "Business Profile",
    summary: "Cocok untuk bisnis lokal yang ingin menjelaskan layanan, harga, proses, area kerja, FAQ, lokasi, dan kontak WhatsApp dalam website yang lebih lengkap.",
    price: "Rp699.000",
    estimate: "3-5 hari setelah materi lengkap",
    revisions: "2x revisi",
    renewal: "Rp399.000 per tahun",
    warranty: "14 hari",
    assistLimit: "Dukungan teknis prioritas via WhatsApp selama masa garansi",
    assistActive: "Masa garansi aktif selama 14 hari setelah rilis",
    includes: [
      "1 halaman website lengkap",
      "7-9 section",
      "copywriting dibantu Sector One",
      "struktur layanan bisnis",
      "daftar harga atau paket bisnis",
      "FAQ / Tanya Jawab",
      "area layanan atau jangkauan",
      "galeri foto sederhana",
      "Google Maps embed",
      "tombol WhatsApp",
      "tampilan responsif mobile",
      "bantuan setup domain jika klien sudah punya domain",
    ],
    assistNotes: [
      "Paling direkomendasikan untuk bisnis lokal, laundry, barbershop, bengkel, klinik kecil, dan kuliner rumahan.",
      "Pembayaran awal 50% sebelum mulai, pelunasan 50% sebelum website dirilis.",
    ],
    domainHosting:
      "Bantuan setup domain pribadi jika klien sudah memiliki domain. Biaya sewa domain pribadi dari penyedia domain ditanggung klien.",
    constraints: [
      "Tidak termasuk biaya pembelian domain pribadi.",
      "Tidak mencakup halaman tambahan (hanya 1 halaman terstruktur).",
      "Tidak mencakup desain custom dari nol (menggunakan layout standar siap pakai).",
      "Tidak termasuk fitur admin, toko online, katalog kompleks, atau payment gateway.",
      "Tidak mencakup revisi besar setelah website rilis, meeting panjang, atau perubahan konsep.",
    ],
  },
  {
    slug: "business-plus",
    name: "Business Plus",
    summary: "Untuk bisnis yang butuh beberapa halaman agar profil, layanan, galeri, dan kontak terlihat lebih tertata.",
    price: "Rp1.499.000",
    estimate: "5-10 hari setelah materi lengkap",
    revisions: "3x revisi",
    renewal: "Rp499.000 per tahun",
    warranty: "30 hari",
    assistLimit: "Dukungan teknis prioritas via WhatsApp selama masa garansi",
    assistActive: "Masa garansi aktif selama 30 hari setelah rilis",
    includes: [
      "3-5 halaman website (Home, Tentang, Layanan, Galeri/Produk, Kontak)",
      "copywriting lebih rapi",
      "struktur SEO dasar",
      "optimasi responsif mobile",
      "bantuan setup domain pribadi",
      "bantuan deploy ke platform hosting",
      "tombol WhatsApp jelas",
      "Google Maps embed",
    ],
    assistNotes: [
      "Cocok untuk bisnis berkembang yang butuh pemisahan halaman agar profil lebih profesional.",
      "Pembayaran awal 50% sebelum mulai, pelunasan 50% sebelum website dirilis.",
    ],
    domainHosting:
      "Termasuk bantuan setting DNS untuk menghubungkan domain pribadi dan bantuan setup ke server hosting yang disepakati.",
    constraints: [
      "Tidak termasuk biaya pembelian domain pribadi dan langganan hosting tahunan.",
      "Tidak mencakup fitur dashboard khusus, admin panel kompleks, atau database dinamis.",
      "Tidak termasuk toko online dengan integrasi payment gateway otomatis.",
      "Tidak mencakup revisi besar di luar batas, meeting panjang, atau perubahan konsep total setelah disetujui.",
    ],
  },
  {
    slug: "custom-website",
    name: "Custom Website",
    summary: "Untuk bisnis yang membutuhkan struktur, halaman, dan fitur lebih spesifik seperti katalog produk, booking, dashboard, atau form khusus.",
    price: "Mulai Rp2.500.000",
    estimate: "Menyesuaikan proyek",
    revisions: "4x revisi",
    renewal: "Menyesuaikan resource",
    warranty: "60 hari",
    assistLimit: "Dukungan teknis dan pemeriksaan sistem setelah rilis",
    assistActive: "Masa garansi aktif selama 60 hari setelah rilis",
    includes: [
      "halaman dan struktur sesuai kebutuhan",
      "katalog produk / layanan terstruktur",
      "sistem pemesanan atau booking sederhana",
      "formulir kontak / input khusus",
      "dashboard admin ringan bila diperlukan",
      "desain UI kustom / terarah",
      "integrasi WhatsApp atau email khusus",
      "optimasi performa dan SEO teknis dasar",
    ],
    assistNotes: [
      "Cocok untuk kebutuhan spesifik seperti multi-cabang, katalog dinamis, sistem reservasi, atau form registrasi.",
      "Pembayaran awal 50% sebelum mulai, pelunasan 50% sebelum website dirilis.",
    ],
    domainHosting:
      "Spesifikasi hosting, domain kustom, dan integrasi teknis disesuaikan dengan kebutuhan resource aplikasi.",
    constraints: [
      "Harga final mengikuti kompleksitas halaman, database, fitur, integrasi, dan kebutuhan maintenance.",
    ],
  },
];

export const serviceNotes = {
  estimateStartsAfter: [
    "pembayaran awal diterima sesuai kesepakatan",
    "ruang lingkup pekerjaan disepakati",
    "materi utama diterima (logo, foto, daftar layanan, harga, nomor WhatsApp, dll)",
    "akses domain atau hosting diberikan bila sudah ada",
  ],
  assistRevisionIncludes: [
    "perbaikan ejaan dan susunan kalimat",
    "penyesuaian urutan section",
    "penggantian foto yang masih dalam ruang lingkup",
    "penyesuaian warna minor",
    "perbaikan tautan WhatsApp atau email",
    "penyesuaian tampilan responsif mobile",
  ],
  assistRevisionExcludes: [
    "penambahan fitur baru di luar kesepakatan",
    "penggantian konsep desain total setelah arah visual disetujui",
    "integrasi pihak ketiga yang belum tertulis di brief",
    "pembuatan logo baru dari nol",
    "penulisan ulang seluruh konten setelah materi final disetujui",
    "pembangunan ulang struktur halaman setelah rilis",
  ],
  annualRenewalCovers: [
    "perpanjangan hosting website (jika dikelola Sector One)",
    "pemeliharaan sertifikat keamanan SSL",
    "backup berkala sesuai kemampuan server",
    "bantuan teknis ringan terkait akses website",
  ],
  aiUsage: [
    "Biaya tahunan menjaga website tetap online dan terpelihara.",
    "Pengingat perpanjangan dikirim sebelum masa aktif berakhir.",
    "Kepemilikan domain tetap atas nama pemilik bisnis setelah seluruh kewajiban selesai.",
  ],
  warrantyExcludes: [
    "kesalahan informasi dari materi yang dikirim klien",
    "perubahan harga atau promo yang belum diinformasikan",
    "gangguan penyedia hosting, domain, atau layanan pihak ketiga",
    "kerusakan akibat perubahan kode oleh pihak luar",
    "penambahan fitur baru di luar kesepakatan awal",
  ],
};

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
